spring.application.name=moodflix

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true`
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# JPA Auditing
spring.jpa.properties.hibernate.envers.audit_table_suffix=_aud

# Security JWT Configuration
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=86400000

# OpenAPI Documentation
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# OpenWeather
app.api.openweathermap.key=${OPENWEATHER_API_KEY}
app.api.openweathermap.url="https://api.openweathermap.org"

# Server Port
server.port=8080

logging.level.org.springframework.security=DEBUG
